{{- $spec := .Values.spec }}
{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $spec.destination.namespace }}
    server: {{ $spec.destination.server }}
  project: default
  source:
    path: src/{{ . }}
    repoURL: {{ $spec.source.repoURL }}
    targetRevision: {{ $spec.source.targetRevision }}
{{- end }}
