---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cartservice
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'cartservice:latest'
  source:
    contextDir: 'src/cartservice/src'
    git:
      ref: main
      uri: https://github.com/paulbarfuss/microservices-demo
    type: Git
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cartservice
spec:
  lookupPolicy:
    local: true
