---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: emailservice
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'emailservice:latest'
  source:
    contextDir: 'src/emailservice/'
    git:
      ref: master
      uri: https://github.com/paulbarfuss/microservices-demo
    type: Git
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: emailservice
spec:
  lookupPolicy:
    local: true
