---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'frontend:latest'
  source:
    contextDir: 'src/frontend/'
    git:
      ref: main
      uri: https://github.com/paulbarfuss/microservices-demo
    type: Git
  strategy:
    type: Docker
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
spec:
  lookupPolicy:
    local: true
