{{- $ns := .Values.applicationNamespace }}
{{- $spec := .Values.spec }}
{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: {{ $ns }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $spec.destination.namespace }}
    server: {{ $spec.destination.server }}
  project: default
  source:
    path: openshift-manifests/deploy/{{ $app }}
    repoURL: {{ $spec.source.repoURL }}
    targetRevision: {{ $spec.source.targetRevision }}
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m0s
      limit: 2
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true   
{{- end }}
