{{- if .Values.serviceMesh.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ServiceMesh
  namespace: {{ .Values.applicationNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: istio-manifests
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m0s
      limit: 2
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true   
{{- end }}
