namespace: microservices-demo
enableBuilds: true

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/paulbarfuss/microservices-demo
    targetRevision: openshift-install

applications:
  - adservice
  - cartservice
  - checkoutservice
  - currencyservice
  - emailservice
  - frontend
  - loadgenerator
  - paymentservice
  - productcatalogservice
  - recommendationservice
  - shippingservice
