buildConfig:
  enabled: True

spec:
  destination:
    namespace: microservices-demo
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/paulbarfuss/microservices-demo
    targetRevision: openshift-install
